services:
  app:
    build: .
    user: ${UID}:${GID}
    working_dir: /app
    volumes:
      - ./:/app:cached
      - ~/.composer-docker/cache:/root/.composer/cache:delegated,consistent
    ports:
      - '30080:80'
